# Generated by Django 5.0.3 on 2024-03-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('feedback', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[(None, 'select gender'), ('Male', 'Male'), ('Female', 'Female')], default=None, max_length=12)),
                ('age', models.IntegerField(max_length=3)),
                ('address', models.TextField()),
                ('phnNo', models.IntegerField(default='', verbose_name='Contact_No')),
            ],
        ),
    ]
