# Generated by Django 5.0.3 on 2024-04-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labregister',
            name='DocName',
            field=models.CharField(default='', max_length=20, verbose_name='DocName'),
        ),
    ]
